# Generated by Django 2.2.6 on 2019-12-17 21:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weixin_core', '0003_auto_20190531_1205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bkweixinuser',
            options={'verbose_name': '微信用户', 'verbose_name_plural': '微信用户'},
        ),
        migrations.AlterField(
            model_name='bkweixinuser',
            name='avatar_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='bkweixinuser',
            name='city',
            field=models.CharField(blank=True, max_length=63, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='bkweixinuser',
            name='country',
            field=models.CharField(blank=True, max_length=63, verbose_name='国家'),
        ),
        migrations.AlterField(
            model_name='bkweixinuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='加入时间'),
        ),
        migrations.AlterField(
            model_name='bkweixinuser',
            name='gender',
            field=models.CharField(blank=True, max_length=15, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='bkweixinuser',
            name='name',
            field=models.CharField(blank=True, max_length=127, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='bkweixinuser',
            name='province',
            field=models.CharField(blank=True, max_length=63, verbose_name='省份'),
        ),
        migrations.AlterField(
            model_name='bkweixinuser',
            name='userid',
            field=models.CharField(max_length=128, unique=True, verbose_name='微信用户在应用里的唯一标识(公众号openid/企业微信userid)'),
        ),
    ]
